import { MODULE_ID, PRIORITY, SETTINGS } from "../constants.js";
import { forbiddenLandsAdapter } from "../adapters/forbidden-lands.js";
import { repository } from "../data/repository.js";
import { getProperty, randomId, warn } from "../utils.js";
import { director } from "../visions/director.js";
import { scheduler } from "../visions/scheduler.js";
import { visibilityService } from "../visibility/visibility-service.js";

export class TriggerService {
  constructor(){this.cooldowns=new Map();this.recent=[];this.registered=false;this.adapters=[forbiddenLandsAdapter];this.regionPatchMode="uninitialized";this.regionWrapperPath=null;this.regionDirectPatch=null;this.triggerRevision=null;this.triggerTypes=new Set();}
  refreshTriggerIndex(){const state=repository.getState();if(this.triggerRevision===state.revision)return;this.triggerTypes.clear();for(const set of Object.values(state.sets))for(const trigger of set.triggers??[])if(trigger.enabled)this.triggerTypes.add(trigger.type);this.triggerRevision=state.revision;}
  hasTriggerType(type){this.refreshTriggerIndex();return this.triggerTypes.has(type);}
  hasAnyTrigger(types){this.refreshTriggerIndex();return types.some(type=>this.triggerTypes.has(type));}
  eligibleTriggeredSets(type,{allowGM=false}={}){if(!this.hasTriggerType(type)||game.user?.isGM&&!allowGM)return[];const sets=game.user?.isGM?repository.getSets():scheduler.eligibleSets();return sets.filter(set=>(set.triggers??[]).some(trigger=>trigger.enabled&&trigger.type===type));}
  async firePrepared(type,context,sets){const results=[];for(const set of sets)for(const trigger of set.triggers??[]){if(!trigger.enabled||trigger.type!==type)continue;const key=`${set.uuid}:${trigger.id}`;if((this.cooldowns.get(key)??0)>Date.now()||!this.matches(trigger,context)||Math.random()>trigger.chance)continue;if(trigger.cooldown>0)this.cooldowns.set(key,Date.now()+trigger.cooldown*1000);const result=await director.enqueueSet(set,{source:`trigger:${type}`,priority:PRIORITY.TRIGGER,conflict:"queue",forced:true,metadata:{triggerId:trigger.id,context:this.sanitize(context)}});results.push(result);this.recent.unshift({id:randomId(8),at:new Date().toISOString(),type,setUuid:set.uuid,triggerId:trigger.id,status:result?.status??"unknown"});this.recent.length=Math.min(this.recent.length,100);}return results;}
  async fire(type,context={},options={}){const sets=this.eligibleTriggeredSets(type,options);return sets.length?this.firePrepared(type,context,sets):[];}
  matches(trigger,context){const c=trigger.config??{};if(c.sceneId&&c.sceneId!==canvas?.scene?.id&&c.sceneId!==context.sceneId)return false;if(c.actorId&&c.actorId!==context.actorId&&c.actorId!==context.actor?.id)return false;if(c.userId&&c.userId!==game.user?.id&&c.userId!==context.userId)return false;if(c.regionId&&c.regionId!==context.regionId&&c.regionId!==context.region?.id)return false;if(c.tokenId&&c.tokenId!==context.tokenId&&c.tokenId!==context.token?.id)return false;if(c.contains&&!JSON.stringify(this.sanitize(context)).toLowerCase().includes(String(c.contains).toLowerCase()))return false;if(c.path){const value=getProperty(context,c.path);if(c.equals!==undefined&&c.equals!==""&&String(value)!==String(c.equals))return false;if(c.minimum!==undefined&&c.minimum!==""&&Number(value)<Number(c.minimum))return false;if(c.maximum!==undefined&&c.maximum!==""&&Number(value)>Number(c.maximum))return false;}return true;}
  sanitize(context){return{sceneId:context.sceneId??canvas?.scene?.id??null,actorId:context.actorId??context.actor?.id??null,tokenId:context.tokenId??context.token?.id??null,targetTokenId:context.targetTokenId??context.targetToken?.id??null,distance:Number.isFinite(Number(context.distance))?Number(context.distance):null,regionId:context.regionId??context.region?.id??null,userId:context.userId??null,combatId:context.combatId??context.combat?.id??null,round:context.round??context.combat?.round??null,turn:context.turn??context.combat?.turn??null,messageId:context.messageId??context.message?.id??null,darkness:context.darkness??null,banes:context.banes??null,damage:Number.isFinite(Number(context.damage))?Number(context.damage):null,attribute:context.attribute??null,previous:Number.isFinite(Number(context.previous))?Number(context.previous):null,value:Number.isFinite(Number(context.value))?Number(context.value):null,system:context.system??null,event:context.event??null};}
  measureDistance(a,b){try{const origin=a?.center??{x:Number(a?.x??0),y:Number(a?.y??0)},destination=b?.center??{x:Number(b?.x??0),y:Number(b?.y??0)};const measured=canvas?.grid?.measurePath?.([origin,destination]);if(Number.isFinite(measured?.distance))return measured.distance;return Math.hypot(destination.x-origin.x,destination.y-origin.y)/Math.max(1,Number(canvas?.grid?.size??100))*Number(canvas?.scene?.grid?.distance??1);}catch(_error){return Infinity;}}
  fireProximity(token){
    if(game.user?.isGM||!this.hasTriggerType("tokenApproach"))return;const moving=token?.object??canvas?.tokens?.get?.(token?.id);if(!moving)return;const sets=this.eligibleTriggeredSets("tokenApproach");if(!sets.length)return;
    for(const target of visibilityService.getOtherworldlyDocuments()){if(target.id===token.id)continue;const distance=this.measureDistance(moving,target.object??canvas?.tokens?.get?.(target.id));if(Number.isFinite(distance))void this.firePrepared("tokenApproach",{token,tokenId:token.id,actorId:token.actor?.id,targetToken:target,targetTokenId:target.id,distance,event:"token-approach"},sets);}
  }
  adapterEvents(events,context={}){for(const event of events??[])if(this.hasTriggerType(event.type))void this.fire(event.type,{...context,...event,system:game.system?.id??null});}
  handleRegionEvent(event){const type=event?.name==="tokenEnter"?"regionEnter":event?.name==="tokenExit"?"regionExit":null;if(!type)return null;const region=event.region,token=event.data?.token;if(!region||!token)return null;return this.fire(type,{region,regionId:region.id,token,tokenId:token.id,actorId:token.actor?.id,userId:event.user?.id??event.user??null,event:type==="regionEnter"?"region-enter":"region-exit"});}
  initialize(){for(const adapter of this.adapters)adapter.primeActors?.();return this.patchRegionEvents();}
  patchRegionEvents(){
    if(this.regionPatchMode!=="uninitialized")return this.regionPatchMode;const proto=globalThis.foundry?.documents?.RegionDocument?.prototype;if(!proto||typeof proto._handleEvent!=="function"){this.regionPatchMode="unavailable";return this.regionPatchMode;}
    const service=this,path="foundry.documents.RegionDocument.prototype._handleEvent";
    if(game.modules?.get("lib-wrapper")?.active&&globalThis.libWrapper){try{libWrapper.register(MODULE_ID,path,async function(wrapped,event){const result=await wrapped(event);try{void service.handleRegionEvent(event);}catch(error){warn("Region trigger dispatch failed",error);}return result;},"WRAPPER");this.regionWrapperPath=path;this.regionPatchMode="libWrapper";return this.regionPatchMode;}catch(error){warn("libWrapper Region patch failed",error);}}
    if(!game.settings.get(MODULE_ID,SETTINGS.DIRECT_FALLBACK)){this.regionPatchMode="unavailable";return this.regionPatchMode;}const descriptor=Object.getOwnPropertyDescriptor(proto,"_handleEvent");if(!descriptor||typeof descriptor.value!=="function"||descriptor.configurable===false){this.regionPatchMode="failed";return this.regionPatchMode;}
    this.regionDirectPatch={proto,descriptor};Object.defineProperty(proto,"_handleEvent",{...descriptor,value:async function(event){const result=await descriptor.value.call(this,event);try{void service.handleRegionEvent(event);}catch(error){warn("Region trigger dispatch failed",error);}return result;}});this.regionPatchMode="direct-fallback";return this.regionPatchMode;
  }
  registerHooks(){
    if(this.registered)return;this.registered=true;
    Hooks.on("canvasReady",()=>{if(this.hasTriggerType("sceneReady"))void this.fire("sceneReady",{sceneId:canvas?.scene?.id,event:"canvas-ready"});});
    Hooks.on("updateCombat",(combat,changes)=>{if(("round"in changes||"turn"in changes)&&this.hasTriggerType("turnStart"))void this.fire("turnStart",{combat,round:combat.round,turn:combat.turn});if((changes.active===true||(combat.started&&changes.round===1))&&this.hasTriggerType("combatStart"))void this.fire("combatStart",{combat});if(changes.active===false&&this.hasTriggerType("combatEnd"))void this.fire("combatEnd",{combat});});
    Hooks.on("deleteCombat",combat=>{if(this.hasTriggerType("combatEnd"))void this.fire("combatEnd",{combat});});
    Hooks.on("updateScene",(scene,changes)=>{if("darkness"in changes&&this.hasTriggerType("darknessChanged"))void this.fire("darknessChanged",{sceneId:scene.id,darkness:changes.darkness});});
    Hooks.on("createActor",actor=>{for(const adapter of this.adapters)adapter.primeActor?.(actor);});Hooks.on("deleteActor",actor=>{for(const adapter of this.adapters)adapter.forgetActor?.(actor);});
    Hooks.on("updateActor",(actor,changes)=>{if(this.hasTriggerType("actorUpdated"))void this.fire("actorUpdated",{actor,actorId:actor.id,changes});for(const adapter of this.adapters)this.adapterEvents(adapter.analyzeActorUpdate?.(actor,changes),{actor,actorId:actor.id,changes});});
    Hooks.on("updateToken",(token,changes)=>{if(!["x","y","elevation"].some(key=>Object.hasOwn(changes,key)))return;if(this.hasTriggerType("tokenMoved"))void this.fire("tokenMoved",{token,tokenId:token.id,actorId:token.actor?.id,changes});this.fireProximity(token);});
    Hooks.on("createChatMessage",message=>{const fblTypes=["fblPush","fblBane","fblSpell","fblCritical"];if(this.hasTriggerType("chatMessage"))void this.fire("chatMessage",{message,messageId:message.id});if(this.hasAnyTrigger(fblTypes))for(const adapter of this.adapters)this.adapterEvents(adapter.analyzeChatMessage?.(message),{message,messageId:message.id});});
  }
  reset(){this.cooldowns.clear();this.recent.length=0;}
  destroy(){if(this.regionWrapperPath&&globalThis.libWrapper)try{libWrapper.unregister(MODULE_ID,this.regionWrapperPath);}catch(_error){}this.regionWrapperPath=null;if(this.regionDirectPatch)Object.defineProperty(this.regionDirectPatch.proto,"_handleEvent",this.regionDirectPatch.descriptor);this.regionDirectPatch=null;this.regionPatchMode="destroyed";this.reset();}
  snapshot(){this.refreshTriggerIndex();return{adapters:this.adapters.map(a=>a.snapshot?.()??{active:false}),regionPatchMode:this.regionPatchMode,triggerTypes:[...this.triggerTypes],activeCooldowns:[...this.cooldowns].filter(([,until])=>until>Date.now()).map(([key,until])=>({key,remainingMs:until-Date.now()})),recent:this.recent.slice(0,30)};}
}
export const triggerService=new TriggerService();
