import { PRIORITY } from "../constants.js";
import { forbiddenLandsAdapter } from "../adapters/forbidden-lands.js";
import { repository } from "../data/repository.js";
import { getProperty, randomId } from "../utils.js";
import { director } from "../visions/director.js";
import { scheduler } from "../visions/scheduler.js";

export class TriggerService {
  constructor(){this.cooldowns=new Map();this.recent=[];this.registered=false;this.adapters=[forbiddenLandsAdapter];}
  async fire(type,context={}, {allowGM=false}={}){if(game.user?.isGM&&!allowGM)return[];const sets=game.user?.isGM?repository.getSets():scheduler.eligibleSets();const results=[];for(const set of sets)for(const trigger of set.triggers??[]){if(!trigger.enabled||trigger.type!==type)continue;const key=`${set.uuid}:${trigger.id}`;if((this.cooldowns.get(key)??0)>Date.now()||!this.matches(trigger,context)||Math.random()>trigger.chance)continue;if(trigger.cooldown>0)this.cooldowns.set(key,Date.now()+trigger.cooldown*1000);const result=await director.enqueueSet(set,{source:`trigger:${type}`,priority:PRIORITY.TRIGGER,conflict:"queue",forced:true,metadata:{triggerId:trigger.id,context:this.sanitize(context)}});results.push(result);this.recent.unshift({id:randomId(8),at:new Date().toISOString(),type,setUuid:set.uuid,triggerId:trigger.id,status:result?.status??"unknown"});this.recent.length=Math.min(this.recent.length,100);}return results;}
  matches(trigger,context){const c=trigger.config??{};if(c.sceneId&&c.sceneId!==canvas?.scene?.id&&c.sceneId!==context.sceneId)return false;if(c.actorId&&c.actorId!==context.actorId&&c.actorId!==context.actor?.id)return false;if(c.userId&&c.userId!==game.user?.id&&c.userId!==context.userId)return false;if(c.regionId&&c.regionId!==context.regionId&&c.regionId!==context.region?.id)return false;if(c.tokenId&&c.tokenId!==context.tokenId&&c.tokenId!==context.token?.id)return false;if(c.contains&&!JSON.stringify(this.sanitize(context)).toLowerCase().includes(String(c.contains).toLowerCase()))return false;if(c.path){const value=getProperty(context,c.path);if(c.equals!==undefined&&c.equals!==""&&String(value)!==String(c.equals))return false;if(c.minimum!==undefined&&c.minimum!==""&&Number(value)<Number(c.minimum))return false;if(c.maximum!==undefined&&c.maximum!==""&&Number(value)>Number(c.maximum))return false;}return true;}
  sanitize(context){return{sceneId:context.sceneId??canvas?.scene?.id??null,actorId:context.actorId??context.actor?.id??null,tokenId:context.tokenId??context.token?.id??null,targetTokenId:context.targetTokenId??context.targetToken?.id??null,distance:Number.isFinite(Number(context.distance))?Number(context.distance):null,regionId:context.regionId??context.region?.id??null,userId:context.userId??null,combatId:context.combatId??context.combat?.id??null,round:context.round??context.combat?.round??null,turn:context.turn??context.combat?.turn??null,messageId:context.messageId??context.message?.id??null,darkness:context.darkness??null,banes:context.banes??null,system:context.system??null,event:context.event??null};}
  measureDistance(a,b){try{const origin=a?.center??{x:Number(a?.x??0),y:Number(a?.y??0)},destination=b?.center??{x:Number(b?.x??0),y:Number(b?.y??0)};const measured=canvas?.grid?.measurePath?.([origin,destination]);if(Number.isFinite(measured?.distance))return measured.distance;return Math.hypot(destination.x-origin.x,destination.y-origin.y)/Math.max(1,Number(canvas?.grid?.size??100))*Number(canvas?.scene?.grid?.distance??1);}catch(_error){return Infinity;}}
  fireProximity(token){const moving=token?.object??canvas?.tokens?.get?.(token?.id);if(!moving)return;for(const target of canvas?.scene?.tokens?.contents??[]){if(target.id===token.id||!repository.getOtherworldly(target).enabled)continue;const distance=this.measureDistance(moving,target.object??canvas?.tokens?.get?.(target.id));if(Number.isFinite(distance))void this.fire("tokenApproach",{token,tokenId:token.id,actorId:token.actor?.id,targetToken:target,targetTokenId:target.id,distance,event:"token-approach"});}}
  adapterEvents(events,context={}){for(const event of events??[])void this.fire(event.type,{...context,...event,system:game.system?.id??null});}
  registerHooks(){if(this.registered)return;this.registered=true;Hooks.on("canvasReady",()=>void this.fire("sceneReady",{sceneId:canvas?.scene?.id,event:"canvas-ready"}));Hooks.on("updateCombat",(combat,changes)=>{if("round"in changes||"turn"in changes)void this.fire("turnStart",{combat,round:combat.round,turn:combat.turn});if(changes.active===true||(combat.started&&changes.round===1))void this.fire("combatStart",{combat});if(changes.active===false)void this.fire("combatEnd",{combat});});Hooks.on("deleteCombat",combat=>void this.fire("combatEnd",{combat}));Hooks.on("updateScene",(scene,changes)=>{if("darkness"in changes)void this.fire("darknessChanged",{sceneId:scene.id,darkness:changes.darkness});});Hooks.on("updateActor",(actor,changes)=>{void this.fire("actorUpdated",{actor,actorId:actor.id,changes});for(const adapter of this.adapters)this.adapterEvents(adapter.analyzeActorUpdate?.(actor,changes),{actor,actorId:actor.id,changes});});Hooks.on("updateToken",(token,changes)=>{if(["x","y","elevation"].some(key=>Object.hasOwn(changes,key))){void this.fire("tokenMoved",{token,tokenId:token.id,actorId:token.actor?.id,changes});this.fireProximity(token);}});Hooks.on("tokenEnterRegion",(region,token)=>void this.fire("regionEnter",{region,regionId:region?.id,token,tokenId:token?.id,actorId:token?.actor?.id,event:"region-enter"}));Hooks.on("tokenExitRegion",(region,token)=>void this.fire("regionExit",{region,regionId:region?.id,token,tokenId:token?.id,actorId:token?.actor?.id,event:"region-exit"}));Hooks.on("createChatMessage",message=>{void this.fire("chatMessage",{message,messageId:message.id});for(const adapter of this.adapters)this.adapterEvents(adapter.analyzeChatMessage?.(message),{message,messageId:message.id});});}
  reset(){this.cooldowns.clear();this.recent.length=0;}
  snapshot(){return{adapters:this.adapters.map(a=>a.snapshot?.()??{active:false}),activeCooldowns:[...this.cooldowns].filter(([,until])=>until>Date.now()).map(([key,until])=>({key,remainingMs:until-Date.now()})),recent:this.recent.slice(0,30)};}
}
export const triggerService=new TriggerService();
